package exercise_security.game_api.repository;

import exercise_security.game_api.model.Game;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;
import org.springframework.stereotype.Repository;

import java.util.List;

@Repository
public interface GameRepository extends JpaRepository<Game, Long> {

    // Kom ihåg!
    // public behövs ej. Allt är public i ett interface
    // JPQL (not SQL)
    // Använd Model/Entity namn i Query. Inte databasens tabellnamn. (JPA vill ha det så)

    // 4 ways:
    // 1. 100% autogenerated queries

    // 2. Derived queries (keywords together) 50% automation
    List<Game> findByGenre(String genre);

    // 3. JPQL (instead of SQL)
    @Query("SELECT g FROM Game g WHERE LOWER(g.title) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    List<Game> searchByTitle(@Param("keyword") String keyword);

    @Query("SELECT g FROM Game g WHERE LOWER(g.title) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    Page<Game> searchByTitle2(@Param("keyword") String keyword, Pageable pageable);

    @Query("SELECT g FROM Game g WHERE LOWER(g.genre) LIKE LOWER(CONCAT('%', :keyword, '%'))")
    Page<Game> searchByGenre(@Param("keyword") String keyword, Pageable pageable);

    // 4. SQL-version
    @Query(value = "SELECT GAMES.* FROM games INNER JOIN reviews ON games.id = reviews.game_id WHERE rating > 9", nativeQuery = true)
    Page<Game> searchTopRatedGames(Pageable pageable);

    // 3. JPQL

    // 4. SQL
//    @Query(value = "SELECT * FROM games WHERE LOWER(g.genre) LIKE LOWER(CONCAT('%', :keyword, '%'))", nativeQuery = true)
//    Page<Game> searchByGenreSQL(@Param("keyword") String keyword, Pageable pageable);

}
